# Generated by Django 3.2.5 on 2021-07-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('available_size', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='cakes/%Y/%m/%d')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
